### ISSUE TITLE
2.2.4.3 逃逸序列 (escape sequence) 应该是常说的“转义字符”

### ISSUE THREAD

**Issue by zekexiao** [sxwangzhiwen/zigcndoc#1]
https://github.com/sxwangzhiwen/zigcndoc/blob/73a10abfcaad3362ce05e2d53948fe1a5a10555e/zigcndoc.pd#L308

[维基百科 zh-cn 转义字符](https://zh.wikipedia.org/zh-cn/%E8%BD%AC%E4%B9%89%E5%AD%97%E7%AC%A6)
[维基百科 zh-tw 跳脫字元](https://zh.wikipedia.org/zh-tw/%E8%BD%AC%E4%B9%89%E5%AD%97%E7%AC%A6)

**Comment by sxwangzhiwen** [comment]
是的，你说的很对。这种情况基本上有两种翻译，一种叫转义字符，一种叫逃逸序列。选哪个都可以。我个人偏好逃逸序列，因为字符串中输入 \ 后，后面的相关字符如：\n \r \xAA 等就从普通字符 n r AA 等的解析中逃逸出来，变成控制字符。我个人觉得这个比转义字符更贴切一些。    当然这仅是个人偏好，转义字符也是惯用法，也是对的。
